# Generated by Django 4.2.1 on 2023-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('print', models.IntegerField(max_length=10)),
                ('Discount', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=10)),
                ('Author', models.CharField(max_length=200)),
            ],
        ),
    ]
