# Generated by Django 4.2.1 on 2023-07-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='print',
            new_name='price',
        ),
    ]
